package ch.epicerielacanopee.statistics.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProduitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitAllPropertiesEquals(Produit expected, Produit actual) {
        assertProduitAutoGeneratedPropertiesEquals(expected, actual);
        assertProduitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitAllUpdatablePropertiesEquals(Produit expected, Produit actual) {
        assertProduitUpdatableFieldsEquals(expected, actual);
        assertProduitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitAutoGeneratedPropertiesEquals(Produit expected, Produit actual) {
        assertThat(expected)
            .as("Verify Produit auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitUpdatableFieldsEquals(Produit expected, Produit actual) {
        assertThat(expected)
            .as("Verify Produit relevant properties")
            .satisfies(e -> assertThat(e.getEpicerioId()).as("check epicerioId").isEqualTo(actual.getEpicerioId()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getLastUpdatedDate()).as("check lastUpdatedDate").isEqualTo(actual.getLastUpdatedDate()))
            .satisfies(e -> assertThat(e.getImportedDate()).as("check importedDate").isEqualTo(actual.getImportedDate()))
            .satisfies(e -> assertThat(e.getNom()).as("check nom").isEqualTo(actual.getNom()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getDisponible()).as("check disponible").isEqualTo(actual.getDisponible()))
            .satisfies(e -> assertThat(e.getPrixFournisseur()).as("check prixFournisseur").isEqualTo(actual.getPrixFournisseur()))
            .satisfies(e -> assertThat(e.getHtTtc()).as("check htTtc").isEqualTo(actual.getHtTtc()))
            .satisfies(e -> assertThat(e.getTauxTva()).as("check tauxTva").isEqualTo(actual.getTauxTva()))
            .satisfies(e -> assertThat(e.getMargeProfit()).as("check margeProfit").isEqualTo(actual.getMargeProfit()))
            .satisfies(e -> assertThat(e.getPrixVente()).as("check prixVente").isEqualTo(actual.getPrixVente()))
            .satisfies(e -> assertThat(e.getVendu()).as("check vendu").isEqualTo(actual.getVendu()))
            .satisfies(e -> assertThat(e.getQuantiteParPiece()).as("check quantiteParPiece").isEqualTo(actual.getQuantiteParPiece()))
            .satisfies(e -> assertThat(e.getUnite()).as("check unite").isEqualTo(actual.getUnite()))
            .satisfies(e -> assertThat(e.getPrixParUnite()).as("check prixParUnite").isEqualTo(actual.getPrixParUnite()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getRemarquesInternes()).as("check remarquesInternes").isEqualTo(actual.getRemarquesInternes()))
            .satisfies(e -> assertThat(e.getFournisseur()).as("check fournisseur").isEqualTo(actual.getFournisseur()))
            .satisfies(e -> assertThat(e.getRefFournisseur()).as("check refFournisseur").isEqualTo(actual.getRefFournisseur()))
            .satisfies(e -> assertThat(e.getStock()).as("check stock").isEqualTo(actual.getStock()))
            .satisfies(e -> assertThat(e.getCommandesClients()).as("check commandesClients").isEqualTo(actual.getCommandesClients()))
            .satisfies(e ->
                assertThat(e.getDerniereVerificationDate())
                    .as("check derniereVerificationDate")
                    .isEqualTo(actual.getDerniereVerificationDate())
            )
            .satisfies(e ->
                assertThat(e.getDerniereLivraisonDate()).as("check derniereLivraisonDate").isEqualTo(actual.getDerniereLivraisonDate())
            )
            .satisfies(e -> assertThat(e.getAchatFournisseur()).as("check achatFournisseur").isEqualTo(actual.getAchatFournisseur()))
            .satisfies(e -> assertThat(e.getDernierAchatDate()).as("check dernierAchatDate").isEqualTo(actual.getDernierAchatDate()))
            .satisfies(e ->
                assertThat(e.getDernierAchatQuantite()).as("check dernierAchatQuantite").isEqualTo(actual.getDernierAchatQuantite())
            )
            .satisfies(e -> assertThat(e.getStatsLivraison()).as("check statsLivraison").isEqualTo(actual.getStatsLivraison()))
            .satisfies(e -> assertThat(e.getStatsPerte()).as("check statsPerte").isEqualTo(actual.getStatsPerte()))
            .satisfies(e -> assertThat(e.getStatsVente()).as("check statsVente").isEqualTo(actual.getStatsVente()))
            .satisfies(e -> assertThat(e.getStatsVenteSpeciale()).as("check statsVenteSpeciale").isEqualTo(actual.getStatsVenteSpeciale()))
            .satisfies(e -> assertThat(e.getTags()).as("check tags").isEqualTo(actual.getTags()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitUpdatableRelationshipsEquals(Produit expected, Produit actual) {
        // empty method
    }
}
